# Site settings

title: crosstool-NG
description: [A versatile (cross) toolchain generator]
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://crosstool-ng.github.com' # the base hostname & protocol for your site
github_username: crosstool-ng
license_url: https://raw.githubusercontent.com/crosstool-ng/crosstool-ng/master/COPYING
mailinglist_url: https://sourceware.org/ml/crossgcc/
irc_url: irc://irc.libera.chat/#crosstool-ng
download_url: http://crosstool-ng.org/download/crosstool-ng/

# Build settings

include: ['_pages', '_pages/docs']
exclude: ['sources']

markdown: kramdown

# use 'post' layout for posts by default (so it can be omitted in front matter)
defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: 'posts' # previously `post` in Jekyll 2.2.
    values:
      layout: 'post'
